### ISSUE TITLE
Can't run in tetris android.

### ISSUE THREAD

**Issue by FangWenSheng1** [mikhail-vlasenko/Tetris-AI#8] opened 2022-01-04 01:18 UTC
I use your pre-version can work perfect. But this version can't.
May i ask the next piece position define like your pre-version?
My config below: , Thanks,

CONFIG = {
    # ---------- per run ----------
    'debug status': 1,  # greater is more information, 0 is none
    'key press delay': 0.02,  # increase if facing misclicks, decrease to go faster
    'tetrio garbage': True,
    'starting choices for 2nd': 8,
    # if true, looks at another frame to check for correct piece placement
    # reduces speed, increases robustness
    'confirm placement': True,
    'play safe': False,  # ai is even more robust
    'play for survival': False,  # if true, starts in 'cleaning' mode
    'override delay': False,  # if true, hard places all pieces even when scared

    # ---------- per user ----------
    'display consts': alex,
    'screen width': 1920,
    'screen height': 1080,

    # ---------- per game ----------
    'game': 'original',
    'playing field size': [20, 10],
    'piece colors': original_colors,
    'extra rows': 0,  # in some Tetrises (tetr.io) pieces spawn above the main field

    # ---------- other ----------
    'gave warning': True,
}

**Comment by mikhail-vlasenko** [comment] 2022-01-06 13:37
I am not sure I understand your question completely, but you have a problem with the next piece, right? I see you've changed the `piece colors` to `original_colors`, however, the problem might have been that they were in BGR, while the code was set to work with RGB (like the `tetrio_colors`). 
I have pushed a fix now, hopefully, it solves your problem

**Comment by mikhail-vlasenko** [comment] 2022-01-06 13:43
If the problem was with the position of the next piece, you will have to change the `DisplayConsts` instance you are using. 

It used to cover the whole 3 next pieces, but since we only use 1 of them, now it should only include the single next piece. See [example](https://github.com/mikhail-vlasenko/Tetris-AI/blob/master/pixel_pos_example.png) for reference

**Comment by FangWenSheng1** [comment] 2022-01-17 08:37
Hi , I change the config, below:

# in BGR
original_colors = np.zeros((7, 3), np.int)
original_colors[0] = (230, 228, 180)
original_colors[1] = (182, 228, 247)
original_colors[2] = (177, 99, 140)
original_colors[3] = (228, 177, 148)
original_colors[4] = (128, 180, 235)
original_colors[5] = (180, 161, 235)
original_colors[6] = (171, 240, 177)

# tetr.io colors in RGB
tetrio_colors = np.zeros((7, 3), np.int)
tetrio_colors[0] = (36, 214, 150)
tetrio_colors[1] = (210, 171, 42)
tetrio_colors[2] = (212, 67, 195)
tetrio_colors[3] = (70, 56, 200)
tetrio_colors[4] = (217, 96, 48)
tetrio_colors[5] = (222, 44, 63)
tetrio_colors[6] = (131, 210, 42)

# set important pixels for screen recognition
abc = DisplayConsts(128, 484, 62, 239, 158, 163, 266, 277)

tetrio_default = DisplayConsts(128, 484, 62, 239, 158, 163, 266, 277)


CONFIG = {
    # ---------- per run ----------
    'debug status': 1,  # greater is more information, 0 is none
    'key press delay': 0.02,  # increase if facing misclicks, decrease to go faster
    'tetrio garbage': False,
    'starting choices for 2nd': 8,
    # if true, looks at another frame to check for correct piece placement
    # reduces speed, increases robustness
    'confirm placement': True,
    'play safe': False,  # ai is even more robust
    'play for survival': False,  # if true, starts in 'cleaning' mode
    'override delay': False,  # if true, hard places all pieces even when scared

    # ---------- per user ----------
    'display consts': abc,
    'screen width': 1440,
    'screen height': 900,

    # ---------- per game ----------
    'game': 'original',
    'playing field size': [20, 10],
    'piece colors': original_colors,
    'extra rows': 0,  # in some Tetrises (tetr.io) pieces spawn above the main field

    # ---------- other ----------
    'gave warning': False,
}


And change the scan_field.py below:
    dark_boundary = [73, 26, 12]

but shown tetris pieces is not found.


screen capture:
[https://ibb.co/821Fwf4](url)


Thanks

**Comment by mikhail-vlasenko** [comment] 2022-01-17 10:30
Thanks for providing a screenshot. I think your `DisplayConsts` should be fine, but the problem might be with the dark boundary. With the values you set, i expect nothing to be considered too dark, thus the whole field will be considered a piece. Notice that the code has `pixels[:, :, 0] < dark_boundary[0]` and 73 is not less than 73, so background is not 'dark'.
Consider changing dark boundary back to `[130, 100, 90]` and trying again. 

To see what the code sees, you can plug `print(field)` on line 25 of `main.py`

Also, i recommend you to pull the new changes as they change `original_colors` from BGR to RGB and should resolve potential future problems. And see if you can move controls away from playing field, it might confuse the recognition.

**Comment by daniel2644** [comment] 2022-09-15 19:25
What to must change for this tetris?:
https://gyazo.com/b07aa2ed60da1b743bbcbdb64d727b4a
can you help me?

**Comment by mikhail-vlasenko** [comment] 2022-09-17 21:10
@daniel2644 You need to go through the setup described in readme under [How to run](https://github.com/mikhail-vlasenko/Tetris-AI#how-to-run).

Also, if WASD controls don't work for this game, you need to change the key bindings. This can be done in [direct_keys.py](https://github.com/mikhail-vlasenko/Tetris-AI/blob/master/src/direct_keys.py), lines 8 - 14. For hex code reference, use table 90 (first page) [here](https://studylib.net/doc/10745497/appendix-c--keyboard-scan-codes), or, what seems to be a more common way, but which didn't work for us, key codes from [here](https://stackoverflow.com/a/11910555/10919379).

**Comment by daniel2644** [comment] 2022-09-18 13:39
already edited the colors:
# in RGB
original_colors = np.zeros((7, 3), np.int)
original_colors[0] = (1, 212, 251)
original_colors[1] = (184, 111, 253)
original_colors[2] = (255, 177, 9)
original_colors[3] = (25, 249, 174)
original_colors[4] = (253, 242, 35)
original_colors[5] = (186, 247, 4)
original_colors[6] = (253, 98, 218)

# tetr.io colors in RGB
tetrio_colors = np.zeros((7, 3), np.int)
tetrio_colors[0] = (1, 212, 251)
tetrio_colors[1] = (184, 111, 253)
tetrio_colors[2] = (255, 177, 9)
tetrio_colors[3] = (25, 249, 174)
tetrio_colors[4] = (253, 242, 35)
tetrio_colors[5] = (186, 247, 4)
tetrio_colors[6] = (253, 98, 218)
the keys w, a, d work but on my version not have hard drop but only s moves one field
others cfg:
CONFIG = {
    # ---------- per run ----------
    'debug status': 2,  # greater is more information, 0 is none
    'key press delay': 0.02,  # increase if facing misclicks, decrease to go faster
    'tetrio garbage': True,
    'starting choices for 2nd': 8,
    # if true, looks at another frame to check for correct piece placement
    # reduces speed, increases robustness
    'confirm placement': True,
    'play safe': False,  # ai is even more robust
    'play for survival': False,  # if true, starts in 'cleaning' mode
    'override delay': False,  # if true, hard places all pieces even when scared

    # ---------- per user ----------
    'display consts': tetrio_default,
    'screen width': 1440,
    'screen height': 900,

    # ---------- per game ----------
    'game': 'tetr.io',
    'playing field size': [20, 10],
    'piece colors': tetrio_colors,
    'extra rows': -4,  # in some Tetrises (tetr.io) pieces spawn above the main field

    # ---------- other ----------
    'gave warning': False,
}
and cannot detect the game board:
Compilation complete

Tetris piece is not found.
Are you sure you have set your DisplayConsts in config.py?

**Comment by mikhail-vlasenko** [comment] 2022-09-18 14:09
@daniel2644 have you edited this line in config?

`tetrio_default = DisplayConsts(279, 1203, 1046, 1512, 370, 420, 1640, 1710, 180)`?

you need to set it according to this example https://github.com/mikhail-vlasenko/Tetris-AI/blob/master/pixel_pos_example.png

**Comment by mikhail-vlasenko** [comment] 2022-09-18 14:17
also, you can add `print(field)` right after it is set in the while loop to see exactly what the agent sees

**Comment by daniel2644** [comment] 2022-09-19 14:44
Could you send me a video on how to accurately set Display Costs?
I know that everything is written there but I am doing something wrong because it still does not detect the field if you don't have time
I will understand and try to look for something else

**Comment by mikhail-vlasenko** [comment] 2022-09-20 13:02
I don't think the video will add anything, I really think there should be enough information to set the display consts.

I recommend 2 things to you:
1. Try running the bot on the game it surely works for: https://tetr.io/ Having a working example will really help you out with understanding how things work. You will only have to set display consts, and import [these](https://github.com/mikhail-vlasenko/Tetris-AI/blob/master/tetrio_config.ttc) settings to tetrio. at least from what I recall. (play solo mode to test the bot)
2.  Take a look at the functions `get_field` and `simplified` in `scan_field.py`. Particularly, 
```python 
img = np.array(screen_capture.grab(monitor))
pixels = simplified(CONFIG['display consts'].get_field_from_screen(img)) 
```
Look at the results of `simplified` and `CONFIG['display consts'].get_field_from_screen(img)` and compare it to what you expect to see.

**Comment by daniel2644** [comment] 2022-09-30 12:47
I just have a problem with this setting Display Costs all the time and I do not know if I am doing it correctly because I have never dealt with it on my tetris version once the bot has detected all the figures but it has a problem with the board I will add you a screen showing what I was taking pixels X and Y is it good Display or maybe you have to type differently? https://gyazo.com/bbd5a261e8d3e3cb98792272ded5eb8c

**Comment by mikhail-vlasenko** [comment] 2022-09-30 16:56
@daniel2644 the arrows on the picture look correct, however, keep in mind that the problem **may not** be with the DisplayConsts.

Have you followed my advice in the previous message?

also, "a problem with the board" is not clear to me

**Comment by daniel2644** [comment] 2022-09-30 20:14
you are right after checking what you gave me earlier, the display is okay, but there is a problem with the keys and bot does not see all places 0 https://gyazo.com/7b70102b337bfccc80bfce3f2d46835e
for my version of Tetris there is only one spin to the right and no hard drop my all key tetris have type w,a,d, ( s move down one)

**Comment by mikhail-vlasenko** [comment] 2022-09-30 22:12
the zeros problem is discussed in this issue, https://github.com/mikhail-vlasenko/Tetris-AI/issues/8#issuecomment-1014368951
you need to modify the dark boundary cause your background is bright.

The absence of the hard drop should not be a problem: just don't play at the fastest bot speed, then it doesn't use the hard drop.

To get the bot working without the left spin key, you have to modify the `place_piece` function in the `AI` class.

**Comment by daniel2644** [comment] 2022-10-01 14:56
now a problem with spawn piece, bot does not detect it or sometimes does it what i must change now for fix this? https://gyazo.com/ce4725faa34958dc0dbbee58f845eb5a
is it a RGB problem or an delay problem?
I have already made dark boundary and it detects the entire board

**Comment by mikhail-vlasenko** [comment] 2022-10-09 21:49
@daniel2644 I'm sorry but neither of your questions is clear to me

**Comment by daniel2644** [comment] 2022-10-10 14:11
Bot do not recognize the figures in the upper border of the grid, but see all of them in the next spawn https://gyazo.com/a7ae4a9ebc2935fff4247b38dd9d35e8
it only recognizes a square in this boundary

**Comment by mikhail-vlasenko** [comment] 2022-10-12 18:26
as you can see by the look of the field array, the cells of the playing grid are not recognized correctly.

You are correct, for the initial detection of the piece, only a small portion of the grid is analyzed.
Specifically, 4 middle columns (index 3 to 6), only in the top few rows.
`type_of_figure()` in `figures.py`
```
figure = [[arr[0][3], arr[0][4], arr[0][5], arr[0][6]],
          [arr[1][3], arr[1][4], arr[1][5], arr[1][6]]]
```

**Comment by mikhail-vlasenko** [comment] 2022-10-12 18:28
if it is possible, i highly recommend you to change the game background

**Comment by mikhail-vlasenko** [comment] 2022-12-07 14:05
has been no activity here for a while, so I assume the problem is solved now

**Closed by mikhail-vlasenko** 2022-12-07 14:05 UTC
